<?php
/*
==================================================================
FILE: index.php
PURPOSE: This is the main homepage for the website.
HOW IT WORKS:
1. It defines a custom page title.
2. It includes the 'header.php' template (which shows the nav bar).
3. It shows the main content for the homepage (hero, products, etc.).
4. It includes the 'footer.php' template (which closes the page).
==================================================================
*/

// 1. Set the page title
// This $pageTitle variable will be "read" by header.php
$pageTitle = "Home - DragonStone";

// 2. Include the reusable header
// This single line prints the entire <head> and <nav> section.
include 'header.php';
?>

<!--
The <main> tag holds all the content that is *unique* to this page.
The header and footer are outside of this.
-->
<main>

    <!-- === HERO SECTION === -->
    <!-- This is the big banner at the top of the homepage. -->
    <!-- [cite: user's uploaded image 'WhatsApp Image 2025-10-20 at 16.19.45_dfac0e4e.jpg'] -->
    <section class="hero-section">
        <h1>Sustainable Living, Made Simple</h1>
        <p>Discover eco-friendly products from small suppliers, join our community, and make a positive impact on the planet.</p>
        <!-- The "Shop Now" button should ideally go to a "shop.php" page,
             but for now, index.php is okay. -->
        <a href="index.php" class="btn btn-primary">Shop Now</a>
        <a href="about.php" class="btn btn-secondary">Learn More</a>
    </section>

    <!-- === VALUE PROPOSITIONS SECTION === -->
    <!-- This is the section with the three icons. -->
    <!-- [cite: user's uploaded image 'WhatsApp Image 2025-10-20 at 16.19.45_dfac0e4e.jpg'] -->
    <section class="value-section">
        <div class="value-item">
            <h3>Eco-Friendly</h3>
            <p>All products are sustainably sourced and verified.</p>
        </div>
        <div class="value-item">
            <h3>Small Suppliers</h3>
            <p>Support local and small businesses making a difference.</p>
        </div>
        <div class="value-item">
            <h3>Community Tips</h3>
            <p>Join challenges, earn EcoPoints, and learn from members.</p>
        </div>
    </section>

    <!-- === BEST SELLERS SECTION === -->
    <!-- This section is "dynamic", meaning its content
         is generated by PHP from the database. -->
    <section class="product-section">
        <h2>Best Sellers</h2>
        <div class="product-grid">

            <?php
            /*
            ------------------------------------------------------------------
            SECTION 3: Dynamic Product Grid
            ------------------------------------------------------------------
            This PHP block "talks" to the database to get the products.
            */
            
            // 1. Include our database connection "key" file.
            // This gives us the '$conn' variable.
            include 'db_connect.php';

            // 2. Write our "question" in SQL.
            // "Select all (using *) columns from the 'products' table."
            $sql = "SELECT * FROM products";
            
            // 3. Send the question to the database and get the results.
            $result = $conn->query($sql);

            // 4. Check if the database sent back at least one product.
            if ($result->num_rows > 0) {
                
                // 5. Loop through each product, one by one.
                // $result->fetch_assoc() grabs one row and puts it in the '$row' variable.
                // The 'while' loop continues as long as there are rows left.
                while($row = $result->fetch_assoc()) {
                    /*
                    6. "Print" (echo) the HTML for each product card.
                    We use the data from the '$row' variable (e.g., $row['name'])
                    to fill in the card's details.
                    */
                    
                    // This <a> tag makes the *entire card* a clickable link.
                    // It links to 'product.php' and passes the product's unique ID
                    // in the URL (e.g., "...?id=1")
                    echo '<a href="product.php?id=' . $row['product_id'] . '" class="product-card-link">';
                    echo '  <div class="product-card">'; // We add the div *inside* the link
                    
                    // The 'src' attribute is filled from the database.
                    // This is why we created the 'images' folder.
                    echo '    <img src="' . $row['image_url'] . '" alt="' . $row['name'] . '" class="product-image">';
                    
                    echo '    <h3>' . $row['name'] . '</h3>';
                    
                    // 'substr()' is a PHP function to cut the text short
                    // (from character 0 to 75) to keep the cards neat.
                    echo '    <p>' . substr($row['description'], 0, 75) . '...</p>';
                    
                    echo '    <span>R ' . $row['price'] . '</span>';
                    echo '  </div>'; // Close the card div
                    echo '</a>'; // Close the link
                }
                
            } else {
                // This 'else' part runs if the 'if ($result->num_rows > 0)' was false.
                echo "<p>No products found.</p>";
            }

            // 7. Close the connection to the database.
            // This is good practice and saves server resources.
            $conn->close();
            ?>

        </div>
    </section>

    <!-- === COMMUNITY CTA SECTION === -->
    <!-- This is a "static" section (just plain HTML). -->
    <!-- [cite: user's uploaded image 'WhatsApp Image 2025-10-20 at 16.19.45_7a94acd2.jpg'] -->
    <section class="cta-section cta-community">
        <h2>Join the DragonStone Community</h2>
        <p>Participate in Eco Challenges, earn EcoPoints, and connect with like-minded individuals.</p>
        <a href="community.php" class="btn btn-secondary">Explore Community</a>
    </section>

    <!-- === SUBSCRIBE CTA SECTION === -->
    <!-- [cite: user's uploaded image 'WhatsApp Image 2025-10-20 at 16.19.45_7a94acd2.jpg'] -->
    <section class="cta-section cta-subscribe">
        <h2>Subscribe & Save</h2>
        <p>Never run out of your favorite eco-friendly products. Subscribe and save up to 15% on every order.</p>
        <a href="index.php" class="btn btn-learn-more">Learn More</a>
    </section>

</main>
<!-- This is the end of the unique content for this page. -->

<?php
// 3. Include the reusable footer
// This single line prints the <footer> and closes the <body> and <html> tags.
include 'footer.php';
?>
